version: 0.2

phases:
  pre_build:
    commands:
      - echo [$(date +"%F %T")] Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo [$(date +"%F %T")] Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME $IMAGE_REPO_NAME
  post_build:
    commands:
      - echo [$(date +"%F %T")] Pushing the Docker image as :latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo [$(date +"%F %T")] Pushing the Docker image as :$CODEBUILD_BUILD_NUMBER
      - docker tag $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
