version: 0.2

phases:
  pre_build:
    commands:
      - echo [$(date +"%F %T")] Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo [$(date +"%F %T")] Building the Docker image...
      - docker build -t $CODEBUILD_BUILD_IMAGE:$CODEBUILD_BUILD_NUMBER .
      - docker tag $CODEBUILD_BUILD_IMAGE:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CODEBUILD_BUILD_IMAGE:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo [$(date +"%F %T")] Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CODEBUILD_BUILD_IMAGE:$CODEBUILD_BUILD_NUMBER
